from app.repositories.data_quality._shared import (
    MVP_COUNTRY_SLUGS as MVP_COUNTRY_SLUGS,
    MVP_SCENARIO_SLUGS as MVP_SCENARIO_SLUGS,
    ONBOARDING_COUNTRY_SLUGS as ONBOARDING_COUNTRY_SLUGS,
    TARGET_PUBLISHED_EVIDENCE_PER_MVP_COUNTRY as TARGET_PUBLISHED_EVIDENCE_PER_MVP_COUNTRY,
    TARGET_PUBLISHED_LEGAL_SIGNALS_PER_MVP_COUNTRY as TARGET_PUBLISHED_LEGAL_SIGNALS_PER_MVP_COUNTRY,
    TARGET_PUBLISHED_SOURCES_PER_MVP_COUNTRY as TARGET_PUBLISHED_SOURCES_PER_MVP_COUNTRY,
    fetch_all as fetch_all,
)
from app.repositories.data_quality.ai import (
    list_ai_drafts_missing_model_metadata as list_ai_drafts_missing_model_metadata,
    list_ai_drafts_with_invalid_draft_type as list_ai_drafts_with_invalid_draft_type,
    list_ai_drafts_with_invalid_status as list_ai_drafts_with_invalid_status,
    list_ai_drafts_without_citations as list_ai_drafts_without_citations,
    list_ai_feature_flags_without_public_access_rules as list_ai_feature_flags_without_public_access_rules,
    list_ai_logs_with_forbidden_metadata_keys as list_ai_logs_with_forbidden_metadata_keys,
    list_approved_ai_drafts_without_review as list_approved_ai_drafts_without_review,
    list_confirmed_contradiction_candidates_without_review as list_confirmed_contradiction_candidates_without_review,
    list_contradiction_candidates_without_traceability as list_contradiction_candidates_without_traceability,
    list_duplicate_qna_votes as list_duplicate_qna_votes,
    list_missing_ai_feature_flags as list_missing_ai_feature_flags,
    list_published_community_answers_without_moderation as list_published_community_answers_without_moderation,
    list_published_community_questions_without_moderation as list_published_community_questions_without_moderation,
    list_published_qna_answers_with_invalid_traceability_refs as list_published_qna_answers_with_invalid_traceability_refs,
    list_published_qna_answers_without_body as list_published_qna_answers_without_body,
    list_published_qna_questions_without_content as list_published_qna_questions_without_content,
    list_published_user_story_ratings_without_moderation as list_published_user_story_ratings_without_moderation,
    list_qna_votes_with_invalid_type as list_qna_votes_with_invalid_type,
    list_stale_pending_data_error_reports as list_stale_pending_data_error_reports,
    list_user_story_ratings_with_invalid_scores as list_user_story_ratings_with_invalid_scores,
)
from app.repositories.data_quality.auth import (
    count_active_owners as count_active_owners,
    list_active_users_missing_password_credential as list_active_users_missing_password_credential,
    list_expired_sessions_not_revoked as list_expired_sessions_not_revoked,
    list_password_credentials_with_invalid_hash_format as list_password_credentials_with_invalid_hash_format,
    list_sessions_with_empty_token_hash as list_sessions_with_empty_token_hash,
    list_suspended_or_deleted_users_with_active_sessions as list_suspended_or_deleted_users_with_active_sessions,
    list_users_with_invalid_role as list_users_with_invalid_role,
    list_users_with_invalid_status as list_users_with_invalid_status,
)
from app.repositories.data_quality.author_metrics import (
    list_author_metric_values_missing_source_or_experience as list_author_metric_values_missing_source_or_experience,
    list_author_metric_values_out_of_scale as list_author_metric_values_out_of_scale,
    list_author_metrics_with_dangling_fork_lineage as list_author_metrics_with_dangling_fork_lineage,
    list_published_author_metrics_without_methodology as list_published_author_metrics_without_methodology,
    list_published_public_author_metrics_text as list_published_public_author_metrics_text,
)
from app.repositories.data_quality.cii import (
    list_cii_metric_definitions_without_polarity as list_cii_metric_definitions_without_polarity,
    list_cii_metric_weights_with_invalid_sum as list_cii_metric_weights_with_invalid_sum,
    list_cii_scenario_scores_missing_formula_metadata as list_cii_scenario_scores_missing_formula_metadata,
    list_cii_scenario_weights_exceeding_one as list_cii_scenario_weights_exceeding_one,
    list_cii_scenario_weights_with_negative_values as list_cii_scenario_weights_with_negative_values,
    list_cii_scores_missing_formula_metadata as list_cii_scores_missing_formula_metadata,
    list_cii_scores_out_of_range as list_cii_scores_out_of_range,
    list_cii_scores_with_non_geometric_aggregation as list_cii_scores_with_non_geometric_aggregation,
    list_inactive_mvp_scenarios as list_inactive_mvp_scenarios,
    list_mvp_countries_missing_cii as list_mvp_countries_missing_cii,
    list_mvp_metrics_missing_values as list_mvp_metrics_missing_values,
    list_mvp_scenarios_missing_cii_scores as list_mvp_scenarios_missing_cii_scores,
    list_mvp_scenarios_missing_cii_weights as list_mvp_scenarios_missing_cii_weights,
)
from app.repositories.data_quality.content import (
    list_country_cards_with_demo_source_summary as list_country_cards_with_demo_source_summary,
    list_country_cards_with_empty_major_sections as list_country_cards_with_empty_major_sections,
    list_evidence_without_country as list_evidence_without_country,
    list_evidence_without_source as list_evidence_without_source,
    list_invalid_synthetic_user_stories as list_invalid_synthetic_user_stories,
    list_missing_country_scores_for_required_scenarios as list_missing_country_scores_for_required_scenarios,
    list_missing_mvp_countries as list_missing_mvp_countries,
    list_mvp_countries_with_too_few_published_evidence as list_mvp_countries_with_too_few_published_evidence,
    list_mvp_countries_with_too_few_published_legal_signals as list_mvp_countries_with_too_few_published_legal_signals,
    list_mvp_countries_with_too_few_published_sources as list_mvp_countries_with_too_few_published_sources,
    list_published_countries_without_cards as list_published_countries_without_cards,
    list_published_countries_without_sources as list_published_countries_without_sources,
    list_published_legal_signals_without_evidence as list_published_legal_signals_without_evidence,
    list_published_legal_signals_without_source as list_published_legal_signals_without_source,
    list_published_legal_signals_without_timeline_event as list_published_legal_signals_without_timeline_event,
    list_published_score_breakdowns_without_source_ids as list_published_score_breakdowns_without_source_ids,
    list_published_sources_with_example_invalid_url as list_published_sources_with_example_invalid_url,
    list_published_sources_with_missing_required_fields as list_published_sources_with_missing_required_fields,
    list_scores_with_incomplete_breakdowns as list_scores_with_incomplete_breakdowns,
    list_scores_with_invalid_weight_sum as list_scores_with_invalid_weight_sum,
    list_scores_without_breakdowns as list_scores_without_breakdowns,
    list_timeline_events_with_country_mismatch as list_timeline_events_with_country_mismatch,
    list_timeline_events_with_invalid_date as list_timeline_events_with_invalid_date,
    list_timeline_events_with_invalid_impact_direction as list_timeline_events_with_invalid_impact_direction,
    list_timeline_events_with_invalid_impact_level as list_timeline_events_with_invalid_impact_level,
    list_timeline_events_without_traceability as list_timeline_events_without_traceability,
    list_unplanned_future_timeline_events as list_unplanned_future_timeline_events,
)
from app.repositories.data_quality.country_contribution import (
    list_proposals_with_non_editor_curator as list_proposals_with_non_editor_curator,
    list_published_proposals_with_inactive_country as list_published_proposals_with_inactive_country,
    list_published_proposals_without_curator as list_published_proposals_without_curator,
)
from app.repositories.data_quality.country_drift import (
    list_active_countries_missing_drift_snapshots as list_active_countries_missing_drift_snapshots,
    list_drift_changed_events_missing_payload_fields as list_drift_changed_events_missing_payload_fields,
    list_drift_snapshots_insufficient_data_inconsistent as list_drift_snapshots_insufficient_data_inconsistent,
    list_drift_snapshots_insufficient_data_with_high_confidence as list_drift_snapshots_insufficient_data_with_high_confidence,
    list_drift_snapshots_missing_computed_at as list_drift_snapshots_missing_computed_at,
    list_drift_snapshots_missing_methodology_version as list_drift_snapshots_missing_methodology_version,
    list_drift_snapshots_with_non_object_input_summary as list_drift_snapshots_with_non_object_input_summary,
    list_duplicate_drift_changed_event_keys as list_duplicate_drift_changed_event_keys,
    list_invalid_drift_snapshot_values as list_invalid_drift_snapshot_values,
)
from app.repositories.data_quality.country_pairs import (
    list_published_pairs_missing_last_verified_at as list_published_pairs_missing_last_verified_at,
    list_published_pairs_without_sources as list_published_pairs_without_sources,
    list_stale_published_pairs as list_stale_published_pairs,
)
from app.repositories.data_quality.decision_passports import (
    list_active_passports_missing_scenario_slug as list_active_passports_missing_scenario_slug,
    list_active_passports_with_empty_candidates as list_active_passports_with_empty_candidates,
    list_active_passports_with_empty_result_snapshot as list_active_passports_with_empty_result_snapshot,
    list_active_passports_with_selected_country_not_in_candidates as list_active_passports_with_selected_country_not_in_candidates,
    list_active_passports_without_sources as list_active_passports_without_sources,
    list_old_active_passports_without_expires_at as list_old_active_passports_without_expires_at,
    list_passports_with_inconsistent_expiry_status as list_passports_with_inconsistent_expiry_status,
)
from app.repositories.data_quality.decision_personalization import (
    list_decision_personalization_feature_flag_mismatches as list_decision_personalization_feature_flag_mismatches,
    list_decision_scores_missing_required_criteria as list_decision_scores_missing_required_criteria,
    list_decision_wizard_rule_mismatches as list_decision_wizard_rule_mismatches,
)
from app.repositories.data_quality.methodology_config import (
    list_invalid_methodology_threshold_order as list_invalid_methodology_threshold_order,
    list_methodology_parameters_out_of_range as list_methodology_parameters_out_of_range,
    list_missing_required_methodology_parameters as list_missing_required_methodology_parameters,
)
from app.repositories.data_quality.migration_board import (
    list_duplicate_pending_migration_board_contact_requests as list_duplicate_pending_migration_board_contact_requests,
    list_invalid_migration_board_blocks as list_invalid_migration_board_blocks,
    list_invalid_migration_board_contact_requests as list_invalid_migration_board_contact_requests,
    list_invalid_migration_board_reports as list_invalid_migration_board_reports,
    list_migration_board_posts_with_route_country_mismatch as list_migration_board_posts_with_route_country_mismatch,
    list_open_threads_without_active_contact as list_open_threads_without_active_contact,
    list_published_migration_board_posts_without_acknowledgements as list_published_migration_board_posts_without_acknowledgements,
    list_published_migration_board_posts_without_approval as list_published_migration_board_posts_without_approval,
    list_published_public_migration_board_posts_text as list_published_public_migration_board_posts_text,
    list_thread_messages_after_block as list_thread_messages_after_block,
    list_thread_messages_after_thread_closed as list_thread_messages_after_thread_closed,
)
from app.repositories.data_quality.personas import (
    list_active_personas_missing_descriptions as list_active_personas_missing_descriptions,
    list_active_personas_missing_metric_modifiers as list_active_personas_missing_metric_modifiers,
    list_active_personas_missing_required_fields as list_active_personas_missing_required_fields,
    list_inactive_personas_with_modifiers as list_inactive_personas_with_modifiers,
    list_persona_adjusted_weight_inputs as list_persona_adjusted_weight_inputs,
    list_persona_modifiers_out_of_range as list_persona_modifiers_out_of_range,
)
from app.repositories.data_quality.platform import (
    list_data_journal_events_referencing_non_public_content as list_data_journal_events_referencing_non_public_content,
    list_data_journal_events_with_internal_payload_fields as list_data_journal_events_with_internal_payload_fields,
    list_disabled_feature_flags_without_access_rules as list_disabled_feature_flags_without_access_rules,
    list_enabled_feature_flags_without_access_rules as list_enabled_feature_flags_without_access_rules,
)
from app.repositories.data_quality.platform_metrics import (
    list_high_confidence_low_sample_metrics as list_high_confidence_low_sample_metrics,
    list_inconsistent_insufficient_data_metrics as list_inconsistent_insufficient_data_metrics,
    list_invalid_platform_metric_values as list_invalid_platform_metric_values,
    list_mvp_countries_missing_global_platform_metrics as list_mvp_countries_missing_global_platform_metrics,
    list_mvp_countries_missing_scenario_risk_metrics as list_mvp_countries_missing_scenario_risk_metrics,
    list_platform_metrics_with_missing_computed_at as list_platform_metrics_with_missing_computed_at,
    list_platform_metrics_with_missing_methodology as list_platform_metrics_with_missing_methodology,
    list_stale_platform_metrics as list_stale_platform_metrics,
)
from app.repositories.data_quality.review import (
    count_domain_events_for_dq as count_domain_events_for_dq,
    list_invalid_domain_events_for_dq as list_invalid_domain_events_for_dq,
    list_mvp_countries_without_legal_events as list_mvp_countries_without_legal_events,
    list_published_evidence_items_with_missing_required_fields as list_published_evidence_items_with_missing_required_fields,
    list_published_legal_signals_with_missing_legal_status as list_published_legal_signals_with_missing_legal_status,
    list_published_legal_signals_with_missing_required_fields as list_published_legal_signals_with_missing_required_fields,
    list_published_legal_signals_with_unknown_legal_status as list_published_legal_signals_with_unknown_legal_status,
    list_review_evidence_items_with_missing_required_fields as list_review_evidence_items_with_missing_required_fields,
    list_review_legal_signals_with_missing_required_fields as list_review_legal_signals_with_missing_required_fields,
    list_review_sources_with_missing_required_fields as list_review_sources_with_missing_required_fields,
)
from app.repositories.data_quality.route_checklists import (
    list_duplicate_step_order_checklist_items as list_duplicate_step_order_checklist_items,
    list_published_checklist_items_missing_title as list_published_checklist_items_missing_title,
)
from app.repositories.data_quality.routes import (
    list_published_routes_missing_legal_status as list_published_routes_missing_legal_status,
    list_published_routes_missing_required_text as list_published_routes_missing_required_text,
    list_published_routes_with_all_eligibility_unknown as list_published_routes_with_all_eligibility_unknown,
    list_published_routes_with_unknown_legal_status as list_published_routes_with_unknown_legal_status,
    list_published_routes_without_documents as list_published_routes_without_documents,
    list_published_routes_without_sources as list_published_routes_without_sources,
    list_route_evidence_country_mismatches as list_route_evidence_country_mismatches,
    list_route_source_country_mismatches as list_route_source_country_mismatches,
)
from app.repositories.data_quality.search_documents import (
    list_active_countries_missing_from_index as list_active_countries_missing_from_index,
    list_published_evidence_missing_from_index as list_published_evidence_missing_from_index,
    list_published_legal_signals_missing_from_index as list_published_legal_signals_missing_from_index,
    list_published_routes_missing_from_index as list_published_routes_missing_from_index,
    list_published_sources_missing_from_index as list_published_sources_missing_from_index,
    list_search_documents_referencing_non_published_content as list_search_documents_referencing_non_published_content,
    list_search_documents_with_incomplete_locale_coverage as list_search_documents_with_incomplete_locale_coverage,
)
from app.repositories.data_quality.telegram_links import (
    list_duplicate_active_telegram_links as list_duplicate_active_telegram_links,
    list_linked_telegram_links_missing_linked_at as list_linked_telegram_links_missing_linked_at,
    list_telegram_links_referencing_missing_users as list_telegram_links_referencing_missing_users,
    list_telegram_links_with_invalid_status as list_telegram_links_with_invalid_status,
    list_unlinked_telegram_links_missing_unlinked_at as list_unlinked_telegram_links_missing_unlinked_at,
)
from app.repositories.data_quality.trip_planner import (
    list_reminders_with_invalid_trip_or_item as list_reminders_with_invalid_trip_or_item,
    list_trip_waypoints_with_invalid_position as list_trip_waypoints_with_invalid_position,
    list_trips_with_invalid_share_state as list_trips_with_invalid_share_state,
)
from app.repositories.data_quality.trust import (
    list_active_countries_missing_trust_scores as list_active_countries_missing_trust_scores,
    list_inconsistent_trust_insufficient_data as list_inconsistent_trust_insufficient_data,
    list_invalid_trust_score_values as list_invalid_trust_score_values,
    list_missing_required_glossary_terms as list_missing_required_glossary_terms,
    list_missing_required_methodology_sections as list_missing_required_methodology_sections,
    list_stale_trust_scores as list_stale_trust_scores,
)
from app.repositories.data_quality.watchlists import (
    list_archived_watchlists_missing_archived_at as list_archived_watchlists_missing_archived_at,
    list_duplicate_active_watchlist_entries as list_duplicate_active_watchlist_entries,
    list_watchlists_referencing_missing_countries as list_watchlists_referencing_missing_countries,
    list_watchlists_referencing_missing_users as list_watchlists_referencing_missing_users,
    list_watchlists_with_invalid_status as list_watchlists_with_invalid_status,
    list_watchlists_with_null_notification_flags as list_watchlists_with_null_notification_flags,
)
from app.repositories.data_quality.what_changed import (
    list_domain_events_referencing_non_published_content as list_domain_events_referencing_non_published_content,
    list_domain_events_with_unknown_country as list_domain_events_with_unknown_country,
)
