from app.core.database import fetch_all as fetch_all
from app.core.mvp_requirements import (
    MVP_CONTENT_DEPTH_TARGETS,
    MVP_COUNTRY_SLUGS as SHARED_MVP_COUNTRY_SLUGS,
    MVP_SCENARIO_SLUGS as SHARED_MVP_SCENARIO_SLUGS,
    ONBOARDING_COUNTRY_SLUGS as SHARED_ONBOARDING_COUNTRY_SLUGS,
)


TARGET_PUBLISHED_SOURCES_PER_MVP_COUNTRY = MVP_CONTENT_DEPTH_TARGETS[
    "published_sources"
]
TARGET_PUBLISHED_EVIDENCE_PER_MVP_COUNTRY = MVP_CONTENT_DEPTH_TARGETS[
    "published_evidence_items"
]
TARGET_PUBLISHED_LEGAL_SIGNALS_PER_MVP_COUNTRY = MVP_CONTENT_DEPTH_TARGETS[
    "published_legal_signals"
]
MVP_COUNTRY_SLUGS = SHARED_MVP_COUNTRY_SLUGS
MVP_SCENARIO_SLUGS = SHARED_MVP_SCENARIO_SLUGS
ONBOARDING_COUNTRY_SLUGS = SHARED_ONBOARDING_COUNTRY_SLUGS
