// Bare, locale-agnostic pathnames. Locale prefixing is handled entirely by
// the `Link`/`useRouter` from `i18n/navigation` (next-intl) at the call
// site — these routes must not embed `?locale=` themselves anymore.
export const routes = {
  home: "/",
  countries: "/countries",
  assistant: "/assistant",
  country: (slug: string) => `/countries/${slug}`,
  decision: "/decision",
  compare: "/compare",
  legalSignals: "/legal-signals",
  legalSignalsTimeline: "/legal-signals/timeline",
  sources: "/sources",
  methodology: "/methodology",
  methodologyParameters: "/methodology/parameters",
  glossary: "/glossary",
  userStories: "/user-stories",
  search: "/search",
  dataQuality: "/internal/data-quality",
  migrationBoardModeration: "/internal/migration-board-moderation",
  communityModeration: "/internal/community-moderation",
  login: "/login",
  register: "/register",
  account: "/account",
  accountMigrationBoard: "/account/migration-board",
  accountAuthorMetrics: "/account/author-metrics",
  authorProfile: (userId: string) => `/authors/${userId}`,
  migrationBoard: "/migration-board",
  migrationBoardNew: "/migration-board/new",
  migrationBoardPost: (id: string) => `/migration-board/${id}`,
  watchlist: "/watchlist",
  subscriptions: "/subscriptions",
  trips: "/trips",
  tripDetail: (id: string) => `/trips/${id}`,
  tripSharedPublic: (token: string) => `/trips/shared/${token}`,
  legalSignalsForCountry: (slug: string) =>
    `/legal-signals?country_slug=${slug}`,
  sourcesForCountry: (slug: string) => `/sources?country_slug=${slug}`,
};
