// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/subscriptions.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramUserId string                 `protobuf:"bytes,1,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	CountrySlug    string                 `protobuf:"bytes,2,opt,name=country_slug,json=countrySlug,proto3" json:"country_slug,omitempty"`
	Active         bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	WebUserId      string                 `protobuf:"bytes,4,opt,name=web_user_id,json=webUserId,proto3" json:"web_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_subscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetTelegramUserId() string {
	if x != nil {
		return x.TelegramUserId
	}
	return ""
}

func (x *Subscription) GetCountrySlug() string {
	if x != nil {
		return x.CountrySlug
	}
	return ""
}

func (x *Subscription) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Subscription) GetWebUserId() string {
	if x != nil {
		return x.WebUserId
	}
	return ""
}

type DeliveryStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventKey       string                 `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	TelegramUserId string                 `protobuf:"bytes,2,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	CountrySlug    string                 `protobuf:"bytes,3,opt,name=country_slug,json=countrySlug,proto3" json:"country_slug,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	SentAt         string                 `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliveryStatus) Reset() {
	*x = DeliveryStatus{}
	mi := &file_proto_subscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatus) ProtoMessage() {}

func (x *DeliveryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatus.ProtoReflect.Descriptor instead.
func (*DeliveryStatus) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryStatus) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *DeliveryStatus) GetTelegramUserId() string {
	if x != nil {
		return x.TelegramUserId
	}
	return ""
}

func (x *DeliveryStatus) GetCountrySlug() string {
	if x != nil {
		return x.CountrySlug
	}
	return ""
}

func (x *DeliveryStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeliveryStatus) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *DeliveryStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramUserId string                 `protobuf:"bytes,1,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CountrySlug    string                 `protobuf:"bytes,3,opt,name=country_slug,json=countrySlug,proto3" json:"country_slug,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_proto_subscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubscriptionRequest) GetTelegramUserId() string {
	if x != nil {
		return x.TelegramUserId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetCountrySlug() string {
	if x != nil {
		return x.CountrySlug
	}
	return ""
}

type DeleteSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramUserId string                 `protobuf:"bytes,1,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	CountrySlug    string                 `protobuf:"bytes,2,opt,name=country_slug,json=countrySlug,proto3" json:"country_slug,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_proto_subscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSubscriptionRequest) GetTelegramUserId() string {
	if x != nil {
		return x.TelegramUserId
	}
	return ""
}

func (x *DeleteSubscriptionRequest) GetCountrySlug() string {
	if x != nil {
		return x.CountrySlug
	}
	return ""
}

type ListSubscriptionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramUserId string                 `protobuf:"bytes,1,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_proto_subscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{4}
}

func (x *ListSubscriptionsRequest) GetTelegramUserId() string {
	if x != nil {
		return x.TelegramUserId
	}
	return ""
}

type GetDeliveryStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramUserId string                 `protobuf:"bytes,1,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	EventKey       string                 `protobuf:"bytes,2,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	CountrySlug    string                 `protobuf:"bytes,3,opt,name=country_slug,json=countrySlug,proto3" json:"country_slug,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_proto_subscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeliveryStatusRequest) GetTelegramUserId() string {
	if x != nil {
		return x.TelegramUserId
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetCountrySlug() string {
	if x != nil {
		return x.CountrySlug
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_proto_subscriptions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *SubscriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_proto_subscriptions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type GetDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DeliveryStatus      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusResponse) Reset() {
	*x = GetDeliveryStatusResponse{}
	mi := &file_proto_subscriptions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusResponse) ProtoMessage() {}

func (x *GetDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriptions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriptions_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeliveryStatusResponse) GetEntries() []*DeliveryStatus {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_subscriptions_proto protoreflect.FileDescriptor

const file_proto_subscriptions_proto_rawDesc = "" +
	"\n" +
	"\x19proto/subscriptions.proto\x12(country_decision_alerts.subscriptions.v1\"\x93\x01\n" +
	"\fSubscription\x12(\n" +
	"\x10telegram_user_id\x18\x01 \x01(\tR\x0etelegramUserId\x12!\n" +
	"\fcountry_slug\x18\x02 \x01(\tR\vcountrySlug\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1e\n" +
	"\vweb_user_id\x18\x04 \x01(\tR\twebUserId\"\xc1\x01\n" +
	"\x0eDeliveryStatus\x12\x1b\n" +
	"\tevent_key\x18\x01 \x01(\tR\beventKey\x12(\n" +
	"\x10telegram_user_id\x18\x02 \x01(\tR\x0etelegramUserId\x12!\n" +
	"\fcountry_slug\x18\x03 \x01(\tR\vcountrySlug\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\asent_at\x18\x05 \x01(\tR\x06sentAt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x84\x01\n" +
	"\x19CreateSubscriptionRequest\x12(\n" +
	"\x10telegram_user_id\x18\x01 \x01(\tR\x0etelegramUserId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fcountry_slug\x18\x03 \x01(\tR\vcountrySlug\"h\n" +
	"\x19DeleteSubscriptionRequest\x12(\n" +
	"\x10telegram_user_id\x18\x01 \x01(\tR\x0etelegramUserId\x12!\n" +
	"\fcountry_slug\x18\x02 \x01(\tR\vcountrySlug\"D\n" +
	"\x18ListSubscriptionsRequest\x12(\n" +
	"\x10telegram_user_id\x18\x01 \x01(\tR\x0etelegramUserId\"\x9a\x01\n" +
	"\x18GetDeliveryStatusRequest\x12(\n" +
	"\x10telegram_user_id\x18\x01 \x01(\tR\x0etelegramUserId\x12\x1b\n" +
	"\tevent_key\x18\x02 \x01(\tR\beventKey\x12!\n" +
	"\fcountry_slug\x18\x03 \x01(\tR\vcountrySlug\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x88\x01\n" +
	"\x14SubscriptionResponse\x12Z\n" +
	"\fsubscription\x18\x01 \x01(\v26.country_decision_alerts.subscriptions.v1.SubscriptionR\fsubscription\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"y\n" +
	"\x19ListSubscriptionsResponse\x12\\\n" +
	"\rsubscriptions\x18\x01 \x03(\v26.country_decision_alerts.subscriptions.v1.SubscriptionR\rsubscriptions\"o\n" +
	"\x19GetDeliveryStatusResponse\x12R\n" +
	"\aentries\x18\x01 \x03(\v28.country_decision_alerts.subscriptions.v1.DeliveryStatusR\aentries2\x8b\x05\n" +
	"\x13SubscriptionService\x12\x99\x01\n" +
	"\x12CreateSubscription\x12C.country_decision_alerts.subscriptions.v1.CreateSubscriptionRequest\x1a>.country_decision_alerts.subscriptions.v1.SubscriptionResponse\x12\x99\x01\n" +
	"\x12DeleteSubscription\x12C.country_decision_alerts.subscriptions.v1.DeleteSubscriptionRequest\x1a>.country_decision_alerts.subscriptions.v1.SubscriptionResponse\x12\x9c\x01\n" +
	"\x11ListSubscriptions\x12B.country_decision_alerts.subscriptions.v1.ListSubscriptionsRequest\x1aC.country_decision_alerts.subscriptions.v1.ListSubscriptionsResponse\x12\x9c\x01\n" +
	"\x11GetDeliveryStatus\x12B.country_decision_alerts.subscriptions.v1.GetDeliveryStatusRequest\x1aC.country_decision_alerts.subscriptions.v1.GetDeliveryStatusResponseB=Z;github.com/country-decision-atlas/notifier/internal/grpc/pbb\x06proto3"

var (
	file_proto_subscriptions_proto_rawDescOnce sync.Once
	file_proto_subscriptions_proto_rawDescData []byte
)

func file_proto_subscriptions_proto_rawDescGZIP() []byte {
	file_proto_subscriptions_proto_rawDescOnce.Do(func() {
		file_proto_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscriptions_proto_rawDesc), len(file_proto_subscriptions_proto_rawDesc)))
	})
	return file_proto_subscriptions_proto_rawDescData
}

var file_proto_subscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_subscriptions_proto_goTypes = []any{
	(*Subscription)(nil),              // 0: country_decision_alerts.subscriptions.v1.Subscription
	(*DeliveryStatus)(nil),            // 1: country_decision_alerts.subscriptions.v1.DeliveryStatus
	(*CreateSubscriptionRequest)(nil), // 2: country_decision_alerts.subscriptions.v1.CreateSubscriptionRequest
	(*DeleteSubscriptionRequest)(nil), // 3: country_decision_alerts.subscriptions.v1.DeleteSubscriptionRequest
	(*ListSubscriptionsRequest)(nil),  // 4: country_decision_alerts.subscriptions.v1.ListSubscriptionsRequest
	(*GetDeliveryStatusRequest)(nil),  // 5: country_decision_alerts.subscriptions.v1.GetDeliveryStatusRequest
	(*SubscriptionResponse)(nil),      // 6: country_decision_alerts.subscriptions.v1.SubscriptionResponse
	(*ListSubscriptionsResponse)(nil), // 7: country_decision_alerts.subscriptions.v1.ListSubscriptionsResponse
	(*GetDeliveryStatusResponse)(nil), // 8: country_decision_alerts.subscriptions.v1.GetDeliveryStatusResponse
}
var file_proto_subscriptions_proto_depIdxs = []int32{
	0, // 0: country_decision_alerts.subscriptions.v1.SubscriptionResponse.subscription:type_name -> country_decision_alerts.subscriptions.v1.Subscription
	0, // 1: country_decision_alerts.subscriptions.v1.ListSubscriptionsResponse.subscriptions:type_name -> country_decision_alerts.subscriptions.v1.Subscription
	1, // 2: country_decision_alerts.subscriptions.v1.GetDeliveryStatusResponse.entries:type_name -> country_decision_alerts.subscriptions.v1.DeliveryStatus
	2, // 3: country_decision_alerts.subscriptions.v1.SubscriptionService.CreateSubscription:input_type -> country_decision_alerts.subscriptions.v1.CreateSubscriptionRequest
	3, // 4: country_decision_alerts.subscriptions.v1.SubscriptionService.DeleteSubscription:input_type -> country_decision_alerts.subscriptions.v1.DeleteSubscriptionRequest
	4, // 5: country_decision_alerts.subscriptions.v1.SubscriptionService.ListSubscriptions:input_type -> country_decision_alerts.subscriptions.v1.ListSubscriptionsRequest
	5, // 6: country_decision_alerts.subscriptions.v1.SubscriptionService.GetDeliveryStatus:input_type -> country_decision_alerts.subscriptions.v1.GetDeliveryStatusRequest
	6, // 7: country_decision_alerts.subscriptions.v1.SubscriptionService.CreateSubscription:output_type -> country_decision_alerts.subscriptions.v1.SubscriptionResponse
	6, // 8: country_decision_alerts.subscriptions.v1.SubscriptionService.DeleteSubscription:output_type -> country_decision_alerts.subscriptions.v1.SubscriptionResponse
	7, // 9: country_decision_alerts.subscriptions.v1.SubscriptionService.ListSubscriptions:output_type -> country_decision_alerts.subscriptions.v1.ListSubscriptionsResponse
	8, // 10: country_decision_alerts.subscriptions.v1.SubscriptionService.GetDeliveryStatus:output_type -> country_decision_alerts.subscriptions.v1.GetDeliveryStatusResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_subscriptions_proto_init() }
func file_proto_subscriptions_proto_init() {
	if File_proto_subscriptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscriptions_proto_rawDesc), len(file_proto_subscriptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscriptions_proto_goTypes,
		DependencyIndexes: file_proto_subscriptions_proto_depIdxs,
		MessageInfos:      file_proto_subscriptions_proto_msgTypes,
	}.Build()
	File_proto_subscriptions_proto = out.File
	file_proto_subscriptions_proto_goTypes = nil
	file_proto_subscriptions_proto_depIdxs = nil
}
