from __future__ import annotations

import hashlib
import json
import re
import sys
import uuid
from dataclasses import dataclass
from pathlib import Path
from psycopg import sql
from utils.synthetic_data.core.world_models import (
    FICTIONAL_NOTICE,
    SyntheticCountry,
    SyntheticLegalSignal,
    SyntheticUser,
    SyntheticWorld,
)


SQL_HEADER_MARKER = (
    f"-- {FICTIONAL_NOTICE} -- generated by utils/synthetic_data"
)

# Owner decision (Stage 2 analytical spike, 2026-07): SyntheticArticle/
# SyntheticComment have no clean real-table analogue (no public
# "articles + comments" concept exists in this schema at all -- see
# utils/synthetic_data/README.md's SQL fixtures section) and stay
# JSON/document-only. SyntheticUser DOES map cleanly onto `users` +
# `user_auth_credentials`, and every synthetic user gets the ordinary
# real `role='user'` regardless of its synthetic author/commenter
# distinction -- testing elevated roles is scripts/create_auth_user.py's
# job, not this generator's.
SYNTHETIC_USER_ROLE = "user"

# A real, working password shared by every synthetic user in a dataset --
# not a secret (this whole dataset is fictional test data), but a fixed,
# documented string so a manual tester or e2e test can actually log in.
# Must satisfy apps/api/app/core/config.py's auth_password_min_length.
SYNTHETIC_USER_PASSWORD = "Synthetic-Test-Password-Not-Real-42017"


@dataclass(frozen=True)
class UserFixtureIds:
    user_id: str
    credential_id: str


_SLUG_SANITIZE_PATTERN = re.compile(r"[^a-z0-9]+")

_LEGAL_SIGNAL_TYPE_BY_METRIC: dict[str, str] = {
    "cost_of_living": "cost_of_living",
    "safety": "safety",
    "civil_freedoms": "freedom",
    "institutional_stability": "rule_of_law",
    "migration_openness": "migration",
}


@dataclass(frozen=True)
class CountryFixtureIds:
    country_id: str
    profile_id: str
    source_id: str
    legal_signal_id: str
    iso2: str
    iso3: str
    slug: str


def _derive_uuid(*parts: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, ":".join(parts)))


def _sanitize_slug(slug: str) -> str:
    sanitized = _SLUG_SANITIZE_PATTERN.sub("-", slug.casefold()).strip("-")
    return sanitized or "synthetic-country"


def _bucket_low_medium_high(value: int) -> str:
    if value < 40:
        return "low"
    if value < 75:
        return "medium"
    return "high"


def _bucket_severity(value: int) -> str:
    if value < 30:
        return "low"
    if value < 60:
        return "medium"
    if value < 85:
        return "high"
    return "critical"


def country_fixture_ids(
    *, dataset_id: str, country: SyntheticCountry, index: int
) -> CountryFixtureIds:
    letter = chr(ord("A") + index)
    return CountryFixtureIds(
        country_id=country.country_id,
        profile_id=_derive_uuid(dataset_id, "profile", country.slug),
        source_id=_derive_uuid(
            dataset_id, "source", country.sources[0].source_id
        ),
        legal_signal_id=_derive_uuid(dataset_id, "legal_signal", country.slug),
        iso2=f"X{letter}",
        iso3=f"X{letter}X",
        slug=_sanitize_slug(country.slug),
    )


def user_fixture_ids(*, dataset_id: str, user: SyntheticUser) -> UserFixtureIds:
    return UserFixtureIds(
        user_id=_derive_uuid(dataset_id, "user", user.user_id),
        credential_id=_derive_uuid(dataset_id, "user_credential", user.user_id),
    )


def _import_real_pbkdf2_params() -> tuple[str, int]:
    """Reuses the real app's own hashing algorithm/iteration count (pure
    constants, no DB connection) so the resulting `password_hash` stays
    verifiable by the real login flow even if the iteration count is ever
    tuned -- same cross-package import pattern already established by
    scripts/create_auth_user.py. Imported lazily: this module is loaded
    whenever dataset_packager.py is (i.e. for generate/render/package),
    and apps/api's own import chain is heavier than anything else
    sql_fixture.py needs."""
    root_dir = Path(__file__).resolve().parents[3]
    api_dir = root_dir / "apps" / "api"
    for import_path in (root_dir, api_dir):
        import_path_str = str(import_path)
        if import_path_str not in sys.path:
            sys.path.insert(0, import_path_str)
    from app.services.auth import PBKDF2_ALGORITHM, PBKDF2_ITERATIONS

    return PBKDF2_ALGORITHM, PBKDF2_ITERATIONS


def _hash_synthetic_password(*, dataset_id: str, user_id: str) -> str:
    """A deterministic stand-in for `app.services.auth.hash_password()`:
    that function salts with `secrets.token_hex()`, which would make
    every fixture regeneration produce a different password_hash for the
    same seed -- breaking this pipeline's core "same seed -> byte-for-
    byte identical world" guarantee. The salt here is derived from
    dataset_id + user_id instead (unique per user, stable across re-runs);
    the algorithm/iteration count still come from the real module, so the
    hash always verifies against the real app's `verify_password()`."""
    algorithm, iterations = _import_real_pbkdf2_params()
    salt = hashlib.sha256(
        f"{dataset_id}:{user_id}:password_salt".encode()
    ).hexdigest()[:32]
    derived = hashlib.pbkdf2_hmac(
        "sha256",
        SYNTHETIC_USER_PASSWORD.encode("utf-8"),
        salt.encode("utf-8"),
        iterations,
    )
    return f"{algorithm}${iterations}${salt}${derived.hex()}"


def _user_metadata(dataset_id: str) -> str:
    return json.dumps(
        {
            "synthetic": True,
            "dataset_id": dataset_id,
            "notice": FICTIONAL_NOTICE,
        }
    )


def _country_summary(world: SyntheticWorld, country: SyntheticCountry) -> str:
    recipe = next(
        (
            recipe
            for recipe in world.document_recipes
            if recipe.country_id == country.country_id
            and recipe.locale == "en-US"
            and recipe.document_type == "country_overview"
        ),
        None,
    )
    if recipe is None:
        return f"Synthetic test country {country.name}. {FICTIONAL_NOTICE}."
    return " ".join(block.text for block in recipe.blocks)


def _legal_signal_type(
    signal: SyntheticLegalSignal, country: SyntheticCountry
) -> str:
    event = next(
        (
            event
            for event in country.events
            if event.event_id == signal.event_id
        ),
        None,
    )
    if event is None:
        return "other"
    return _LEGAL_SIGNAL_TYPE_BY_METRIC.get(event.metric, "other")


def _lit(value: object) -> sql.Composable:
    return sql.Literal(value)


def build_seed_sql(world: SyntheticWorld) -> str:
    """Render an idempotent SQL fixture for `world` without ever opening a
    database connection (spec section 12: generate the file first, connect
    only from a separate, explicit command). Every id is derived
    deterministically from `dataset_id`, so re-running the same dataset's
    fixture against the same database only ever updates its own rows via
    `ON CONFLICT ... DO UPDATE`, never inserting duplicates."""
    dataset_id = world.metadata.dataset_id
    statements: list[sql.Composable] = [
        sql.SQL(SQL_HEADER_MARKER + f" -- dataset_id={dataset_id}\n"),
        sql.SQL("BEGIN;\n"),
    ]

    for index, country in enumerate(world.countries):
        ids = country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        )
        source = country.sources[0]
        legal_signal = next(
            signal
            for signal in world.legal_signals
            if signal.country_id == country.country_id
        )

        statements.append(
            sql.SQL(
                """
INSERT INTO countries (id, slug, iso2, iso3, name, is_active, is_demo)
VALUES ({id}, {slug}, {iso2}, {iso3}, {name}, TRUE, FALSE)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug, iso2 = EXCLUDED.iso2, iso3 = EXCLUDED.iso3,
    name = EXCLUDED.name, is_active = EXCLUDED.is_active,
    is_demo = EXCLUDED.is_demo, updated_at = NOW();
"""
            ).format(
                id=_lit(ids.country_id),
                slug=_lit(ids.slug),
                iso2=_lit(ids.iso2),
                iso3=_lit(ids.iso3),
                name=_lit(country.name),
            )
        )

        statements.append(
            sql.SQL(
                """
INSERT INTO country_profiles (id, country_id, summary, status)
VALUES ({id}, {country_id}, {summary}, 'published')
ON CONFLICT (country_id) DO UPDATE SET
    summary = EXCLUDED.summary, status = EXCLUDED.status, updated_at = NOW();
"""
            ).format(
                id=_lit(ids.profile_id),
                country_id=_lit(ids.country_id),
                summary=_lit(_country_summary(world, country)),
            )
        )

        reliability = _bucket_low_medium_high(source.confidence)
        statements.append(
            sql.SQL(
                """
INSERT INTO sources (
    id, title, url, source_type, publisher, country_id,
    reliability_level, confidence, status
)
VALUES ({id}, {title}, {url}, 'dataset', {publisher}, {country_id},
    {reliability}, {reliability}, 'published')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title, url = EXCLUDED.url, publisher = EXCLUDED.publisher,
    country_id = EXCLUDED.country_id, reliability_level = EXCLUDED.reliability_level,
    confidence = EXCLUDED.confidence, status = EXCLUDED.status, updated_at = NOW();
"""
            ).format(
                id=_lit(ids.source_id),
                title=_lit(source.title),
                url=_lit(source.url),
                publisher=_lit(f"Synthetic dataset {dataset_id}"),
                country_id=_lit(ids.country_id),
                reliability=_lit(reliability),
            )
        )

        confidence_bucket = _bucket_low_medium_high(legal_signal.confidence)
        severity_bucket = _bucket_severity(legal_signal.confidence)
        sentiment = (
            legal_signal.impact
            if legal_signal.impact in ("positive", "negative")
            else "neutral"
        )
        statements.append(
            sql.SQL(
                """
INSERT INTO legal_signals (
    id, country_id, title, summary, signal_type, sentiment, severity,
    status, confidence_level, effective_date, published_at,
    impact_direction, impact_level, source_id, confidence, legal_status
)
VALUES ({id}, {country_id}, {title}, {summary}, {signal_type}, {sentiment},
    {severity}, 'published', {confidence}, {effective_date}, {effective_date},
    {sentiment}, {severity}, {source_id}, {confidence}, 'effective')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title, summary = EXCLUDED.summary,
    signal_type = EXCLUDED.signal_type, sentiment = EXCLUDED.sentiment,
    severity = EXCLUDED.severity, status = EXCLUDED.status,
    confidence_level = EXCLUDED.confidence_level,
    effective_date = EXCLUDED.effective_date,
    published_at = EXCLUDED.published_at,
    impact_direction = EXCLUDED.impact_direction,
    impact_level = EXCLUDED.impact_level, source_id = EXCLUDED.source_id,
    confidence = EXCLUDED.confidence, legal_status = EXCLUDED.legal_status,
    updated_at = NOW();
"""
            ).format(
                id=_lit(ids.legal_signal_id),
                country_id=_lit(ids.country_id),
                title=_lit(f"{country.name}: {legal_signal.impact} signal"),
                summary=_lit(
                    f"Synthetic legal signal for {country.name}. {FICTIONAL_NOTICE}."
                ),
                signal_type=_lit(_legal_signal_type(legal_signal, country)),
                sentiment=_lit(sentiment),
                severity=_lit(severity_bucket),
                confidence=_lit(confidence_bucket),
                effective_date=_lit(legal_signal.effective_as_of),
                source_id=_lit(ids.source_id),
            )
        )

    if world.users:
        metadata = _user_metadata(dataset_id)
        for user in world.users:
            user_ids = user_fixture_ids(dataset_id=dataset_id, user=user)
            password_hash = _hash_synthetic_password(
                dataset_id=dataset_id, user_id=user.user_id
            )
            statements.append(
                sql.SQL(
                    """
INSERT INTO users (id, email, display_name, role, status, metadata)
VALUES ({id}, {email}, {display_name}, {role}, 'active', {metadata}::jsonb)
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email, display_name = EXCLUDED.display_name,
    role = EXCLUDED.role, status = EXCLUDED.status,
    metadata = EXCLUDED.metadata, updated_at = NOW();
"""
                ).format(
                    id=_lit(user_ids.user_id),
                    email=_lit(user.email),
                    display_name=_lit(user.display_name),
                    role=_lit(SYNTHETIC_USER_ROLE),
                    metadata=_lit(metadata),
                )
            )
            statements.append(
                sql.SQL(
                    """
INSERT INTO user_auth_credentials (
    id, user_id, credential_type, password_hash, password_updated_at
)
VALUES ({id}, {user_id}, 'password', {password_hash}, NOW())
ON CONFLICT (user_id, credential_type) DO UPDATE SET
    password_hash = EXCLUDED.password_hash, password_updated_at = NOW(),
    updated_at = NOW();
"""
                ).format(
                    id=_lit(user_ids.credential_id),
                    user_id=_lit(user_ids.user_id),
                    password_hash=_lit(password_hash),
                )
            )

    statements.append(sql.SQL("COMMIT;\n"))
    return "\n".join(statement.as_string(None) for statement in statements)


def build_cleanup_sql(world: SyntheticWorld) -> str:
    """Render a cleanup script that deletes only this dataset's own rows,
    identified by their deterministic ids, and never touches the schema,
    other datasets, or the conserved demo countries (belt-and-suspenders
    `is_demo = FALSE` guard on top of the id list, spec section 11.1-11.2)."""
    dataset_id = world.metadata.dataset_id
    country_ids = [country.country_id for country in world.countries]
    profile_ids = [
        country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        ).profile_id
        for index, country in enumerate(world.countries)
    ]
    source_ids = [
        country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        ).source_id
        for index, country in enumerate(world.countries)
    ]
    legal_signal_ids = [
        country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        ).legal_signal_id
        for index, country in enumerate(world.countries)
    ]
    user_ids = [
        user_fixture_ids(dataset_id=dataset_id, user=user).user_id
        for user in world.users
    ]
    credential_ids = [
        user_fixture_ids(dataset_id=dataset_id, user=user).credential_id
        for user in world.users
    ]

    def _id_list(ids: list[str]) -> sql.Composable:
        return sql.SQL(", ").join(_lit(value) for value in ids)

    statements = [
        sql.SQL(SQL_HEADER_MARKER + f" -- cleanup dataset_id={dataset_id}\n"),
        sql.SQL("BEGIN;\n"),
        sql.SQL("DELETE FROM legal_signals WHERE id IN ({ids});\n").format(
            ids=_id_list(legal_signal_ids)
        ),
        sql.SQL("DELETE FROM sources WHERE id IN ({ids});\n").format(
            ids=_id_list(source_ids)
        ),
        sql.SQL("DELETE FROM country_profiles WHERE id IN ({ids});\n").format(
            ids=_id_list(profile_ids)
        ),
        sql.SQL(
            "DELETE FROM countries WHERE id IN ({ids}) AND is_demo = FALSE;\n"
        ).format(ids=_id_list(country_ids)),
    ]
    if credential_ids:
        statements.append(
            sql.SQL(
                "DELETE FROM user_auth_credentials WHERE id IN ({ids});\n"
            ).format(ids=_id_list(credential_ids))
        )
    if user_ids:
        statements.append(
            sql.SQL("DELETE FROM users WHERE id IN ({ids});\n").format(
                ids=_id_list(user_ids)
            )
        )
    statements.append(sql.SQL("COMMIT;\n"))
    return "\n".join(statement.as_string(None) for statement in statements)
