from __future__ import annotations

import re
import uuid
from dataclasses import dataclass
from psycopg import sql
from utils.synthetic_data.core.world_models import (
    FICTIONAL_NOTICE,
    SyntheticCountry,
    SyntheticLegalSignal,
    SyntheticWorld,
)


SQL_HEADER_MARKER = (
    f"-- {FICTIONAL_NOTICE} -- generated by utils/synthetic_data"
)

_SLUG_SANITIZE_PATTERN = re.compile(r"[^a-z0-9]+")

_LEGAL_SIGNAL_TYPE_BY_METRIC: dict[str, str] = {
    "cost_of_living": "cost_of_living",
    "safety": "safety",
    "civil_freedoms": "freedom",
    "institutional_stability": "rule_of_law",
    "migration_openness": "migration",
}


@dataclass(frozen=True)
class CountryFixtureIds:
    country_id: str
    profile_id: str
    source_id: str
    legal_signal_id: str
    iso2: str
    iso3: str
    slug: str


def _derive_uuid(*parts: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, ":".join(parts)))


def _sanitize_slug(slug: str) -> str:
    sanitized = _SLUG_SANITIZE_PATTERN.sub("-", slug.casefold()).strip("-")
    return sanitized or "synthetic-country"


def _bucket_low_medium_high(value: int) -> str:
    if value < 40:
        return "low"
    if value < 75:
        return "medium"
    return "high"


def _bucket_severity(value: int) -> str:
    if value < 30:
        return "low"
    if value < 60:
        return "medium"
    if value < 85:
        return "high"
    return "critical"


def country_fixture_ids(
    *, dataset_id: str, country: SyntheticCountry, index: int
) -> CountryFixtureIds:
    letter = chr(ord("A") + index)
    return CountryFixtureIds(
        country_id=country.country_id,
        profile_id=_derive_uuid(dataset_id, "profile", country.slug),
        source_id=_derive_uuid(
            dataset_id, "source", country.sources[0].source_id
        ),
        legal_signal_id=_derive_uuid(dataset_id, "legal_signal", country.slug),
        iso2=f"X{letter}",
        iso3=f"X{letter}X",
        slug=_sanitize_slug(country.slug),
    )


def _country_summary(world: SyntheticWorld, country: SyntheticCountry) -> str:
    recipe = next(
        (
            recipe
            for recipe in world.document_recipes
            if recipe.country_id == country.country_id
            and recipe.locale == "en-US"
            and recipe.document_type == "country_overview"
        ),
        None,
    )
    if recipe is None:
        return f"Synthetic test country {country.name}. {FICTIONAL_NOTICE}."
    return " ".join(block.text for block in recipe.blocks)


def _legal_signal_type(
    signal: SyntheticLegalSignal, country: SyntheticCountry
) -> str:
    event = next(
        (
            event
            for event in country.events
            if event.event_id == signal.event_id
        ),
        None,
    )
    if event is None:
        return "other"
    return _LEGAL_SIGNAL_TYPE_BY_METRIC.get(event.metric, "other")


def _lit(value: object) -> sql.Composable:
    return sql.Literal(value)


def build_seed_sql(world: SyntheticWorld) -> str:
    """Render an idempotent SQL fixture for `world` without ever opening a
    database connection (spec section 12: generate the file first, connect
    only from a separate, explicit command). Every id is derived
    deterministically from `dataset_id`, so re-running the same dataset's
    fixture against the same database only ever updates its own rows via
    `ON CONFLICT ... DO UPDATE`, never inserting duplicates."""
    dataset_id = world.metadata.dataset_id
    statements: list[sql.Composable] = [
        sql.SQL(SQL_HEADER_MARKER + f" -- dataset_id={dataset_id}\n"),
        sql.SQL("BEGIN;\n"),
    ]

    for index, country in enumerate(world.countries):
        ids = country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        )
        source = country.sources[0]
        legal_signal = next(
            signal
            for signal in world.legal_signals
            if signal.country_id == country.country_id
        )

        statements.append(
            sql.SQL(
                """
INSERT INTO countries (id, slug, iso2, iso3, name, is_active, is_demo)
VALUES ({id}, {slug}, {iso2}, {iso3}, {name}, TRUE, FALSE)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug, iso2 = EXCLUDED.iso2, iso3 = EXCLUDED.iso3,
    name = EXCLUDED.name, is_active = EXCLUDED.is_active,
    is_demo = EXCLUDED.is_demo, updated_at = NOW();
"""
            ).format(
                id=_lit(ids.country_id),
                slug=_lit(ids.slug),
                iso2=_lit(ids.iso2),
                iso3=_lit(ids.iso3),
                name=_lit(country.name),
            )
        )

        statements.append(
            sql.SQL(
                """
INSERT INTO country_profiles (id, country_id, summary, status)
VALUES ({id}, {country_id}, {summary}, 'published')
ON CONFLICT (country_id) DO UPDATE SET
    summary = EXCLUDED.summary, status = EXCLUDED.status, updated_at = NOW();
"""
            ).format(
                id=_lit(ids.profile_id),
                country_id=_lit(ids.country_id),
                summary=_lit(_country_summary(world, country)),
            )
        )

        reliability = _bucket_low_medium_high(source.confidence)
        statements.append(
            sql.SQL(
                """
INSERT INTO sources (
    id, title, url, source_type, publisher, country_id,
    reliability_level, confidence, status
)
VALUES ({id}, {title}, {url}, 'dataset', {publisher}, {country_id},
    {reliability}, {reliability}, 'published')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title, url = EXCLUDED.url, publisher = EXCLUDED.publisher,
    country_id = EXCLUDED.country_id, reliability_level = EXCLUDED.reliability_level,
    confidence = EXCLUDED.confidence, status = EXCLUDED.status, updated_at = NOW();
"""
            ).format(
                id=_lit(ids.source_id),
                title=_lit(source.title),
                url=_lit(source.url),
                publisher=_lit(f"Synthetic dataset {dataset_id}"),
                country_id=_lit(ids.country_id),
                reliability=_lit(reliability),
            )
        )

        confidence_bucket = _bucket_low_medium_high(legal_signal.confidence)
        severity_bucket = _bucket_severity(legal_signal.confidence)
        sentiment = (
            legal_signal.impact
            if legal_signal.impact in ("positive", "negative")
            else "neutral"
        )
        statements.append(
            sql.SQL(
                """
INSERT INTO legal_signals (
    id, country_id, title, summary, signal_type, sentiment, severity,
    status, confidence_level, effective_date, published_at,
    impact_direction, impact_level, source_id, confidence, legal_status
)
VALUES ({id}, {country_id}, {title}, {summary}, {signal_type}, {sentiment},
    {severity}, 'published', {confidence}, {effective_date}, {effective_date},
    {sentiment}, {severity}, {source_id}, {confidence}, 'effective')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title, summary = EXCLUDED.summary,
    signal_type = EXCLUDED.signal_type, sentiment = EXCLUDED.sentiment,
    severity = EXCLUDED.severity, status = EXCLUDED.status,
    confidence_level = EXCLUDED.confidence_level,
    effective_date = EXCLUDED.effective_date,
    published_at = EXCLUDED.published_at,
    impact_direction = EXCLUDED.impact_direction,
    impact_level = EXCLUDED.impact_level, source_id = EXCLUDED.source_id,
    confidence = EXCLUDED.confidence, legal_status = EXCLUDED.legal_status,
    updated_at = NOW();
"""
            ).format(
                id=_lit(ids.legal_signal_id),
                country_id=_lit(ids.country_id),
                title=_lit(f"{country.name}: {legal_signal.impact} signal"),
                summary=_lit(
                    f"Synthetic legal signal for {country.name}. {FICTIONAL_NOTICE}."
                ),
                signal_type=_lit(_legal_signal_type(legal_signal, country)),
                sentiment=_lit(sentiment),
                severity=_lit(severity_bucket),
                confidence=_lit(confidence_bucket),
                effective_date=_lit(legal_signal.effective_as_of),
                source_id=_lit(ids.source_id),
            )
        )

    statements.append(sql.SQL("COMMIT;\n"))
    return "\n".join(statement.as_string(None) for statement in statements)


def build_cleanup_sql(world: SyntheticWorld) -> str:
    """Render a cleanup script that deletes only this dataset's own rows,
    identified by their deterministic ids, and never touches the schema,
    other datasets, or the conserved demo countries (belt-and-suspenders
    `is_demo = FALSE` guard on top of the id list, spec section 11.1-11.2)."""
    dataset_id = world.metadata.dataset_id
    country_ids = [country.country_id for country in world.countries]
    profile_ids = [
        country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        ).profile_id
        for index, country in enumerate(world.countries)
    ]
    source_ids = [
        country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        ).source_id
        for index, country in enumerate(world.countries)
    ]
    legal_signal_ids = [
        country_fixture_ids(
            dataset_id=dataset_id, country=country, index=index
        ).legal_signal_id
        for index, country in enumerate(world.countries)
    ]

    def _id_list(ids: list[str]) -> sql.Composable:
        return sql.SQL(", ").join(_lit(value) for value in ids)

    statements = [
        sql.SQL(SQL_HEADER_MARKER + f" -- cleanup dataset_id={dataset_id}\n"),
        sql.SQL("BEGIN;\n"),
        sql.SQL("DELETE FROM legal_signals WHERE id IN ({ids});\n").format(
            ids=_id_list(legal_signal_ids)
        ),
        sql.SQL("DELETE FROM sources WHERE id IN ({ids});\n").format(
            ids=_id_list(source_ids)
        ),
        sql.SQL("DELETE FROM country_profiles WHERE id IN ({ids});\n").format(
            ids=_id_list(profile_ids)
        ),
        sql.SQL(
            "DELETE FROM countries WHERE id IN ({ids}) AND is_demo = FALSE;\n"
        ).format(ids=_id_list(country_ids)),
        sql.SQL("COMMIT;\n"),
    ]
    return "\n".join(statement.as_string(None) for statement in statements)
